version: "3.4"

networks:
  servicenet:
    driver: overlay
    ipam:
      config:
        -
          subnet: 10.0.9.0/24

configs:
  hydra_logging_svcs_config:
    file: ../config/hydra-logging-svcs.conf
  hydra_router_config:
    file: ../config/hydra-router-config.json
  website_svcs_config:
    file: ../config/config.json

services:
  hydra-router:
    image: flywheelsports/hydra-router:1.6.20
    depends_on:
      - redis
      - hydra-logging-svcs
    networks:
      - servicenet
    extra_hosts:
      - "host:${HOST_IP}"
    configs:
      - source: hydra_router_config
        target: /usr/src/app/config/config.json
    ports:
      - target: 80
        published: 5353
        protocol: tcp
        mode: ingress
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 6
      # resources:
      #   limits:
      #     memory: 256M

  hydra-logging-svcs:
    image: flywheelsports/hydra-logging-svcs:0.2.4
    depends_on:
      - redis
    networks:
      - servicenet
    extra_hosts:
      - "host:${HOST_IP}"
    configs:
      - source: hydra_logging_svcs_config
        target: /usr/src/app/config/config.json
    ports:
      - target: 12000
        published: 12000
        protocol: tcp
        mode: ingress
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 6
      resources:
        limits:
          memory: 128M

  website-svcs:
    image: iash/website-svcs:0.3.1
    depends_on:
      - redis
      - hydra-logging-svcs
    networks:
      - servicenet
    extra_hosts:
      - "host:${HOST_IP}"
    configs:
      - source: website_svcs_config
        target: /usr/src/app/config/config.json
    ports:
      - target: 80
        published: 9000
        protocol: tcp
        mode: ingress
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 6
      # resources:
      #   limits:
      #     memory: 256M
