version: "3.4"

networks:
  servicenet:
    driver: overlay
    ipam:
      config:
        -
          subnet: 10.0.9.0/24

services:
  ai-service:
    image: pnxtech/ai-service:0.1.0
    networks:
      - servicenet
    extra_hosts:
      - "host:${HOST_IP}"
    ports:
      - target: 5000
        published: 5000
        protocol: tcp
        mode: ingress
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 6
